version: '3.3'
services:
  db:
    image: mariadb:10.7.7-focal
    container_name: db
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    env_file:
      - .env

  wp:
    depends_on:
      - db
    image: wordpress:6.1.1-php8.2-fpm-alpine
    container_name: wp
    restart: always
    user: "root:root"
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./wp:/var/www/html
      - ./plugin:/var/www/html/wp-data/plugins/

  lb:
    image: caddy:2.6.2-alpine
    container_name: lb
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./wp:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
